# Generated by Django 5.2 on 2025-05-08 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0011_remove_quizquestion_correct_choice_quizchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomyMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.specialty')),
            ],
        ),
    ]
