# Generated by Django 5.2 on 2025-05-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anatomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
