# Generated by Django 5.2 on 2025-05-09 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anatomy', '0002_anatomysystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anatomymain',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anatomy.anatomysystem'),
        ),
    ]
