# Generated by Django 5.2 on 2025-05-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anatomy', '0003_alter_anatomymain_system'),
        ('instruments', '0011_remove_quizquestion_correct_choice_quizchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='anatomysystem',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.specialty'),
        ),
    ]
