# Generated by Django 5.2 on 2025-05-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anatomy', '0004_anatomysystem_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anatomymain',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
