# Generated by Django 5.2 on 2025-05-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anatomy', '0005_alter_anatomymain_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='anatomymain',
            name='model_embed_code1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomymain',
            name='model_embed_code2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomymain',
            name='model_embed_code3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomymain',
            name='model_embed_code4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
