# Generated by Django 5.2 on 2025-05-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anatomy', '0006_anatomymain_model_embed_code1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anatomymain',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomymain',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomymain',
            name='description3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomymain',
            name='description4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
