# Generated by Django 5.2 on 2025-04-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
