# Generated by Django 5.2 on 2025-04-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_specialty_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
