# Generated by Django 5.2 on 2025-04-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_instrumenttype_remove_instrument_specialties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='specialty',
            field=models.ManyToManyField(related_name='instruments', to='instruments.specialty'),
        ),
    ]
