# Generated by Django 5.2 on 2025-04-30 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_alter_instrument_specialty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='specialty',
            new_name='specialties',
        ),
    ]
