# Generated by Django 5.2 on 2025-04-30 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_rename_specialty_instrument_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumenttype'),
        ),
    ]
