# Generated by Django 5.2 on 2025-05-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0007_instrument_instrument_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='model_embed_code',
            new_name='model_embed_code1',
        ),
        migrations.AddField(
            model_name='instrument',
            name='model_embed_code2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='model_embed_code3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
