# Generated by Django 5.2 on 2025-05-05 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0008_rename_model_embed_code_instrument_model_embed_code1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument_NameAndDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specificInstrument', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('instrumentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumenttype')),
            ],
        ),
    ]
