# Generated by Django 5.2 on 2025-05-05 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0009_instrument_nameanddescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='notes',
        ),
    ]
